PHR-11742 don't send letter invitations to under-16s
patientsknowbest/pkb-common pull request #100
Opened 2023-08-24 12:37 UTC by jimmymcfox

2023-08-24 13:43 UTC, pkbdevdeploy reviewed
Version `66-head-d719c47-338776-SNAPSHOT` was generated from commit `d719c47b1235acbba619c8e1136f7eabd8101759`

2023-08-24 13:44 UTC, idasbiste requested changes
The method looks good but I would probably rebase this as it is dragging a lot of old commits. Also, I have left a question about possible unnecessary properties in the util pom.

2023-08-24 13:44 UTC, idasbiste commented on util/pom.xml
> +        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
Do we specifically need these?

2023-08-25 11:28 UTC, pkbdevdeploy reviewed
Version `66-head-50c32dd-339153-SNAPSHOT` was generated from commit `50c32dd0321663771f6f3313365c68da83e230ca`

2023-08-25 13:53 UTC, closed without merging

2023-08-25 13:53 UTC, jimmymcfox commented
Created new branch, will raise new PR